import type { PlagiaAiToolName } from "./types"

interface MistralToolDef {
  type: "function"
  function: {
    name: PlagiaAiToolName
    description: string
    parameters: Record<string, unknown>
  }
}

export const MISTRAL_TOOLS: MistralToolDef[] = [
  {
    type: "function",
    function: {
      name: "paraphrase",
      description:
        "Rewrite text in different words while preserving meaning. Use when the user wants the same content phrased differently, made more formal, more casual, simpler, more academic, or more creative. Costs text tokens.",
      parameters: {
        type: "object",
        properties: {
          text: {
            type: "string",
            description: "The text to paraphrase. Required.",
          },
          mode: {
            type: "string",
            enum: ["standard", "fluency", "formal", "simple", "creative", "academic"],
            description:
              "The paraphrasing mode. 'standard' = balanced rewrite. 'fluency' = readability. 'formal' = elevated register. 'simple' = plain B1-level vocabulary. 'creative' = more lexical variation. 'academic' = scholarly tone with passive voice and hedges.",
          },
        },
        required: ["text", "mode"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "summarize",
      description:
        "Condense text into a shorter summary. Use when the user wants a TL;DR, the gist, key takeaways, or to make a long text shorter. Costs text tokens.",
      parameters: {
        type: "object",
        properties: {
          text: {
            type: "string",
            description: "The text to summarize. Required.",
          },
          length_percent: {
            type: "integer",
            minimum: 10,
            maximum: 90,
            description:
              "Target summary length as a percentage of the original word count (10-90). Default 30 if user doesn't specify.",
          },
          format: {
            type: "string",
            enum: ["paragraph", "bullets"],
            description:
              "Output format. 'paragraph' = one cohesive paragraph. 'bullets' = 3-7 bullet points.",
          },
        },
        required: ["text", "length_percent", "format"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "humanize",
      description:
        "Rewrite AI-generated text to sound more human and less robotic. Use ONLY when the user explicitly says their text was AI-written or sounds AI-generated and they want it to sound human. Do NOT use as a general rewriting tool — use paraphrase for that. Costs text tokens.",
      parameters: {
        type: "object",
        properties: {
          text: {
            type: "string",
            description: "The AI-generated text to humanize. Required.",
          },
          tone: {
            type: "string",
            enum: ["casual", "professional", "academic", "creative", "friendly"],
            description: "The target tone of the humanized output.",
          },
          level: {
            type: "integer",
            minimum: 0,
            maximum: 100,
            description:
              "Humanization intensity. 0-20 = light edit. 21-50 = moderate. 51-80 = strong restructure. 81-100 = heavy rewrite. Default 50.",
          },
        },
        required: ["text", "tone", "level"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "ai_detect",
      description:
        "Analyze text to determine whether it was written by a human or generated by AI. Returns a percentage likelihood and sentence-by-sentence breakdown. Use when the user asks 'is this AI?', 'was this written by AI?', or wants to verify writing authenticity. Costs text tokens.",
      parameters: {
        type: "object",
        properties: {
          text: {
            type: "string",
            description: "The text to analyze. Required.",
          },
        },
        required: ["text"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "grammar",
      description:
        "Check text for grammar, spelling, and punctuation errors. Returns the corrected text plus a list of specific issues with positions and explanations. Use when the user asks to 'proofread', 'check grammar', 'fix errors', or similar. Costs text tokens.",
      parameters: {
        type: "object",
        properties: {
          text: {
            type: "string",
            description: "The text to check. Required.",
          },
        },
        required: ["text"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "plagiarism_check",
      description:
        "Analyze text for signs of plagiarism — flagging segments that appear copied, heavily reused, or stylistically inconsistent. Use when the user explicitly asks to check for plagiarism, originality, or copied content. Costs text tokens.",
      parameters: {
        type: "object",
        properties: {
          text: {
            type: "string",
            description: "The text to check. Required.",
          },
        },
        required: ["text"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "generate_infographic",
      description:
        "Generate an SVG infographic from source content — title, intro, key stats, sections, and conclusion are extracted automatically. Use when the user wants to turn an article, summary, or topic into a visual infographic. Costs image tokens (paid currency, separate from text tokens) — confirm with the user before calling if unsure.",
      parameters: {
        type: "object",
        properties: {
          source_text: {
            type: "string",
            description:
              "The full source content to turn into an infographic (article, summary, notes, etc.). Required.",
          },
        },
        required: ["source_text"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "generate_chart",
      description:
        "Generate an SVG chart, diagram, or visualization from a natural-language description. Supports bar, line, pie, flowchart, mindmap, timeline, and comparison types. Use when the user asks for a chart, graph, diagram, flowchart, mind map, timeline, or comparison visual. Costs image tokens — confirm with the user before calling if unsure.",
      parameters: {
        type: "object",
        properties: {
          description: {
            type: "string",
            description:
              "A natural-language description of what the chart should show. Required.",
          },
          chart_type: {
            type: "string",
            enum: [
              "auto-detect",
              "bar",
              "line",
              "pie",
              "flowchart",
              "mindmap",
              "timeline",
              "comparison",
            ],
            description:
              "The chart type. 'auto-detect' lets the system pick the best fit. Default 'auto-detect'.",
          },
        },
        required: ["description", "chart_type"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "generate_thumbnail",
      description:
        "Generate a 1200x630 SVG thumbnail / cover image with a title and styled background. Suitable for YouTube covers, OpenGraph images, blog headers. Costs image tokens — confirm with the user before calling if unsure.",
      parameters: {
        type: "object",
        properties: {
          title: {
            type: "string",
            description: "The main title text for the thumbnail. Required.",
          },
          style: {
            type: "string",
            enum: ["modern", "minimal", "bold", "gradient"],
            description: "Visual style of the thumbnail. Default 'modern'.",
          },
        },
        required: ["title", "style"],
      },
    },
  },
]

export function summarizeArgs(name: PlagiaAiToolName, args: Record<string, unknown>): string {
  switch (name) {
    case "paraphrase":
      return `Mode: ${String(args.mode || "standard")}`
    case "summarize":
      return `Length: ${args.length_percent ?? 30}% · ${String(args.format || "paragraph")}`
    case "humanize":
      return `Tone: ${String(args.tone || "casual")} · Level: ${args.level ?? 50}`
    case "ai_detect":
    case "grammar":
    case "plagiarism_check":
      return `${String(args.text || "").length} chars`
    case "generate_infographic":
      return `${String(args.source_text || "").slice(0, 60)}${String(args.source_text || "").length > 60 ? "..." : ""}`
    case "generate_chart":
      return `Type: ${String(args.chart_type || "auto-detect")}`
    case "generate_thumbnail":
      return `Style: ${String(args.style || "modern")}`
  }
}

export function toolDisplayName(name: PlagiaAiToolName): string {
  switch (name) {
    case "paraphrase":
      return "Paraphraser"
    case "summarize":
      return "Summarizer"
    case "humanize":
      return "AI Humanizer"
    case "ai_detect":
      return "AI Detector"
    case "grammar":
      return "Grammar Checker"
    case "plagiarism_check":
      return "Plagiarism Checker"
    case "generate_infographic":
      return "Infographic Generator"
    case "generate_chart":
      return "Chart Generator"
    case "generate_thumbnail":
      return "Thumbnail Generator"
  }
}
