// PDF Report Generator Utility
// Uses browser's built-in print functionality to generate PDFs

interface PlagiarismReportData {
  text: string
  plagiarismPercentage: number
  matches: { text: string; similarity: number }[]
  date: Date
}

interface AIDetectorSentence {
  text: string
  score: number
  type: "human" | "mixed" | "ai"
}

interface AIDetectorReportData {
  text: string
  aiScore: number
  humanLikelihood: string
  analysis: string
  date: Date
  sentences?: AIDetectorSentence[]
}

interface GrammarReportData {
  originalText: string
  correctedText: string
  issues: { type: string; text: string; replacement: string; message: string }[]
  date: Date
}

/**
 * Optional display strings and date locale for a report. Any label left out
 * falls back to its English default, so callers that pass nothing get the
 * original English report.
 */
export interface ReportOptions<Labels> {
  labels?: Partial<Labels>
  /** BCP 47 tag used to format the "Generated on" date. Defaults to "en-US". */
  localeTag?: string
}

export interface PlagiarismReportLabels {
  documentTitle: string
  reportTitle: string
  generatedOn: (date: string) => string
  scoreLabel: string
  words: string
  characters: string
  matchesFound: string
  analyzedText: string
  potentialMatches: (count: number) => string
  matchSimilarity: (similarity: number) => string
  footer: string
}

export interface AIDetectorReportLabels {
  documentTitle: string
  reportTitle: string
  generatedOn: (date: string) => string
  scoreLabel: string
  words: string
  characters: string
  verdict: string
  analysisSummary: string
  sentenceBreakdown: string
  /** Label shown for each sentence type; unknown types are printed as-is. */
  sentenceTypes: Record<AIDetectorSentence["type"], string>
  sentenceScore: (score: number) => string
  analyzedText: string
  footer: string
}

export interface GrammarReportLabels {
  documentTitle: string
  reportTitle: string
  generatedOn: (date: string) => string
  issuesFound: string
  errors: string
  warnings: string
  suggestions: string
  originalText: string
  correctedText: string
  footer: string
}

const DEFAULT_PLAGIARISM_LABELS: PlagiarismReportLabels = {
  documentTitle: "Plagiarism Report - Plagiacheck",
  reportTitle: "Plagiarism Detection Report",
  generatedOn: (date) => `Generated on ${date}`,
  scoreLabel: "Plagiarism Detected",
  words: "Words",
  characters: "Characters",
  matchesFound: "Matches Found",
  analyzedText: "Analyzed Text",
  potentialMatches: (count) => `Potential Matches (${count})`,
  matchSimilarity: (similarity) => `${similarity}% similarity`,
  footer: "This report was generated by Plagiacheck - AI-Powered Plagiarism Detection",
}

const DEFAULT_AI_DETECTOR_LABELS: AIDetectorReportLabels = {
  documentTitle: "AI Detection Report - Plagiacheck",
  reportTitle: "AI Content Detection Report",
  generatedOn: (date) => `Generated on ${date}`,
  scoreLabel: "AI Probability",
  words: "Words",
  characters: "Characters",
  verdict: "Verdict",
  analysisSummary: "Analysis Summary",
  sentenceBreakdown: "Sentence-by-Sentence Breakdown",
  sentenceTypes: { human: "human", mixed: "mixed", ai: "ai" },
  sentenceScore: (score) => `AI score: ${score}%`,
  analyzedText: "Analyzed Text",
  footer: "This report was generated by Plagiacheck - AI-Powered Content Detection",
}

const DEFAULT_GRAMMAR_LABELS: GrammarReportLabels = {
  documentTitle: "Grammar Check Report - Plagiacheck",
  reportTitle: "Grammar Check Report",
  generatedOn: (date) => `Generated on ${date}`,
  issuesFound: "Issues Found",
  errors: "Errors",
  warnings: "Warnings",
  suggestions: "Suggestions",
  originalText: "Original Text",
  correctedText: "Corrected Text",
  footer: "This report was generated by Plagiacheck - AI-Powered Grammar Checker",
}

function formatDate(date: Date, localeTag = "en-US"): string {
  return date.toLocaleDateString(localeTag, {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  })
}

function getBaseStyles(): string {
  return `
    <style>
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }
      body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
        line-height: 1.6;
        color: #1a1a1a;
        padding: 40px;
        max-width: 800px;
        margin: 0 auto;
      }
      .header {
        border-bottom: 3px solid #3b82f6;
        padding-bottom: 20px;
        margin-bottom: 30px;
      }
      .logo {
        font-size: 28px;
        font-weight: bold;
        color: #3b82f6;
      }
      .report-title {
        font-size: 24px;
        margin-top: 10px;
        color: #374151;
      }
      .date {
        color: #6b7280;
        font-size: 14px;
        margin-top: 5px;
      }
      .section {
        margin-bottom: 30px;
      }
      .section-title {
        font-size: 18px;
        font-weight: 600;
        color: #1f2937;
        margin-bottom: 15px;
        padding-bottom: 8px;
        border-bottom: 1px solid #e5e7eb;
      }
      .score-box {
        background: linear-gradient(135deg, #3b82f6 0%, #2563eb 100%);
        color: white;
        padding: 25px;
        border-radius: 12px;
        text-align: center;
        margin-bottom: 20px;
      }
      .score-value {
        font-size: 48px;
        font-weight: bold;
      }
      .score-label {
        font-size: 16px;
        opacity: 0.9;
      }
      .score-green {
        background: linear-gradient(135deg, #10b981 0%, #059669 100%);
      }
      .score-yellow {
        background: linear-gradient(135deg, #f59e0b 0%, #d97706 100%);
      }
      .score-red {
        background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%);
      }
      .text-box {
        background: #f9fafb;
        padding: 20px;
        border-radius: 8px;
        border: 1px solid #e5e7eb;
        white-space: pre-wrap;
        word-wrap: break-word;
        font-size: 14px;
        max-height: 300px;
        overflow: hidden;
      }
      .match-item {
        padding: 15px;
        background: #fef3c7;
        border-left: 4px solid #f59e0b;
        margin-bottom: 10px;
        border-radius: 0 8px 8px 0;
      }
      .match-text {
        font-style: italic;
        color: #92400e;
      }
      .match-similarity {
        font-weight: 600;
        color: #b45309;
        margin-top: 5px;
      }
      .issue-item {
        padding: 12px 15px;
        margin-bottom: 10px;
        border-radius: 8px;
      }
      .issue-error {
        background: #fef2f2;
        border-left: 4px solid #ef4444;
      }
      .issue-warning {
        background: #fffbeb;
        border-left: 4px solid #f59e0b;
      }
      .issue-suggestion {
        background: #eff6ff;
        border-left: 4px solid #3b82f6;
      }
      .issue-message {
        font-size: 14px;
        color: #374151;
      }
      .issue-fix {
        margin-top: 8px;
        font-size: 13px;
      }
      .strike {
        text-decoration: line-through;
        color: #ef4444;
      }
      .replacement {
        color: #10b981;
        font-weight: 500;
      }
      .analysis-box {
        background: #f0fdf4;
        padding: 20px;
        border-radius: 8px;
        border: 1px solid #bbf7d0;
      }
      .footer {
        margin-top: 40px;
        padding-top: 20px;
        border-top: 1px solid #e5e7eb;
        text-align: center;
        color: #6b7280;
        font-size: 12px;
      }
      .stats-grid {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 15px;
        margin-bottom: 20px;
      }
      .stat-item {
        text-align: center;
        padding: 15px;
        background: #f9fafb;
        border-radius: 8px;
      }
      .stat-value {
        font-size: 24px;
        font-weight: bold;
        color: #1f2937;
      }
      .stat-label {
        font-size: 12px;
        color: #6b7280;
        text-transform: uppercase;
      }
      @media print {
        body {
          padding: 20px;
        }
        .text-box {
          max-height: none;
        }
      }
    </style>
  `
}

export function generatePlagiarismReport(
  data: PlagiarismReportData,
  options: ReportOptions<PlagiarismReportLabels> = {}
): boolean {
  const l = { ...DEFAULT_PLAGIARISM_LABELS, ...options.labels }
  const scoreClass = data.plagiarismPercentage < 20 ? "score-green" : data.plagiarismPercentage < 50 ? "score-yellow" : "score-red"

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${escapeHtml(l.documentTitle)}</title>
      ${getBaseStyles()}
    </head>
    <body>
      <div class="header">
        <div class="logo">Plagiacheck</div>
        <div class="report-title">${escapeHtml(l.reportTitle)}</div>
        <div class="date">${escapeHtml(l.generatedOn(formatDate(data.date, options.localeTag)))}</div>
      </div>

      <div class="section">
        <div class="score-box ${scoreClass}">
          <div class="score-value">${data.plagiarismPercentage}%</div>
          <div class="score-label">${escapeHtml(l.scoreLabel)}</div>
        </div>

        <div class="stats-grid">
          <div class="stat-item">
            <div class="stat-value">${data.text.split(/\s+/).filter(Boolean).length}</div>
            <div class="stat-label">${escapeHtml(l.words)}</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${data.text.length}</div>
            <div class="stat-label">${escapeHtml(l.characters)}</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${data.matches.length}</div>
            <div class="stat-label">${escapeHtml(l.matchesFound)}</div>
          </div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">${escapeHtml(l.analyzedText)}</div>
        <div class="text-box">${escapeHtml(data.text.substring(0, 1000))}${data.text.length > 1000 ? "..." : ""}</div>
      </div>

      ${data.matches.length > 0 ? `
      <div class="section">
        <div class="section-title">${escapeHtml(l.potentialMatches(data.matches.length))}</div>
        ${data.matches.map((match) => `
          <div class="match-item">
            <div class="match-text">"${escapeHtml(match.text)}"</div>
            <div class="match-similarity">${escapeHtml(l.matchSimilarity(match.similarity))}</div>
          </div>
        `).join("")}
      </div>
      ` : ""}

      <div class="footer">
        <p>${escapeHtml(l.footer)}</p>
        <p>www.plagiacheck.online</p>
      </div>
    </body>
    </html>
  `

  return openPrintWindow(html)
}

export function generateAIDetectorReport(
  data: AIDetectorReportData,
  options: ReportOptions<AIDetectorReportLabels> = {}
): boolean {
  const l = { ...DEFAULT_AI_DETECTOR_LABELS, ...options.labels }
  const scoreClass = data.aiScore < 30 ? "score-green" : data.aiScore < 70 ? "score-yellow" : "score-red"

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${escapeHtml(l.documentTitle)}</title>
      ${getBaseStyles()}
    </head>
    <body>
      <div class="header">
        <div class="logo">Plagiacheck</div>
        <div class="report-title">${escapeHtml(l.reportTitle)}</div>
        <div class="date">${escapeHtml(l.generatedOn(formatDate(data.date, options.localeTag)))}</div>
      </div>

      <div class="section">
        <div class="score-box ${scoreClass}">
          <div class="score-value">${data.aiScore}%</div>
          <div class="score-label">${escapeHtml(l.scoreLabel)}</div>
        </div>

        <div class="stats-grid">
          <div class="stat-item">
            <div class="stat-value">${data.text.split(/\s+/).filter(Boolean).length}</div>
            <div class="stat-label">${escapeHtml(l.words)}</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${data.text.length}</div>
            <div class="stat-label">${escapeHtml(l.characters)}</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${data.humanLikelihood}</div>
            <div class="stat-label">${escapeHtml(l.verdict)}</div>
          </div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">${escapeHtml(l.analysisSummary)}</div>
        <div class="analysis-box">
          <p>${escapeHtml(data.analysis)}</p>
        </div>
      </div>

      ${data.sentences && data.sentences.length > 0 ? `
      <div class="section">
        <div class="section-title">${escapeHtml(l.sentenceBreakdown)}</div>
        ${data.sentences.map((s) => {
          const cls = s.type === "ai" ? "issue-error" : s.type === "mixed" ? "issue-warning" : "issue-suggestion"
          const labelColor = s.type === "ai" ? "#b91c1c" : s.type === "mixed" ? "#b45309" : "#1d4ed8"
          const typeLabel = Object.prototype.hasOwnProperty.call(l.sentenceTypes, s.type)
            ? escapeHtml(l.sentenceTypes[s.type])
            : s.type
          return `
            <div class="issue-item ${cls}">
              <div class="issue-message">${escapeHtml(s.text)}</div>
              <div class="issue-fix">
                <strong style="color: ${labelColor}; text-transform: uppercase;">${typeLabel}</strong>
                <span style="margin-left: 8px; color: #6b7280;">${escapeHtml(l.sentenceScore(s.score))}</span>
              </div>
            </div>
          `
        }).join("")}
      </div>
      ` : ""}

      <div class="section">
        <div class="section-title">${escapeHtml(l.analyzedText)}</div>
        <div class="text-box">${escapeHtml(data.text.substring(0, 1000))}${data.text.length > 1000 ? "..." : ""}</div>
      </div>

      <div class="footer">
        <p>${escapeHtml(l.footer)}</p>
        <p>www.plagiacheck.online</p>
      </div>
    </body>
    </html>
  `

  return openPrintWindow(html)
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
}

export function generateGrammarReport(
  data: GrammarReportData,
  options: ReportOptions<GrammarReportLabels> = {}
): boolean {
  const l = { ...DEFAULT_GRAMMAR_LABELS, ...options.labels }
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${escapeHtml(l.documentTitle)}</title>
      ${getBaseStyles()}
    </head>
    <body>
      <div class="header">
        <div class="logo">Plagiacheck</div>
        <div class="report-title">${escapeHtml(l.reportTitle)}</div>
        <div class="date">${escapeHtml(l.generatedOn(formatDate(data.date, options.localeTag)))}</div>
      </div>

      <div class="section">
        <div class="score-box ${data.issues.length === 0 ? "score-green" : data.issues.length < 5 ? "score-yellow" : "score-red"}">
          <div class="score-value">${data.issues.length}</div>
          <div class="score-label">${escapeHtml(l.issuesFound)}</div>
        </div>

        <div class="stats-grid">
          <div class="stat-item">
            <div class="stat-value">${data.issues.filter(i => i.type === "error").length}</div>
            <div class="stat-label">${escapeHtml(l.errors)}</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${data.issues.filter(i => i.type === "warning").length}</div>
            <div class="stat-label">${escapeHtml(l.warnings)}</div>
          </div>
          <div class="stat-item">
            <div class="stat-value">${data.issues.filter(i => i.type === "suggestion").length}</div>
            <div class="stat-label">${escapeHtml(l.suggestions)}</div>
          </div>
        </div>
      </div>

      ${data.issues.length > 0 ? `
      <div class="section">
        <div class="section-title">${escapeHtml(l.issuesFound)}</div>
        ${data.issues.map((issue) => `
          <div class="issue-item issue-${["error", "warning", "suggestion"].includes(issue.type) ? issue.type : "suggestion"}">
            <div class="issue-message">${escapeHtml(issue.message)}</div>
            <div class="issue-fix">
              <span class="strike">${escapeHtml(issue.text)}</span>
              <span> → </span>
              <span class="replacement">${escapeHtml(issue.replacement)}</span>
            </div>
          </div>
        `).join("")}
      </div>
      ` : ""}

      <div class="section">
        <div class="section-title">${escapeHtml(l.originalText)}</div>
        <div class="text-box">${escapeHtml(data.originalText.substring(0, 800))}${data.originalText.length > 800 ? "..." : ""}</div>
      </div>

      <div class="section">
        <div class="section-title">${escapeHtml(l.correctedText)}</div>
        <div class="text-box" style="background: #f0fdf4; border-color: #bbf7d0;">${escapeHtml(data.correctedText.substring(0, 800))}${data.correctedText.length > 800 ? "..." : ""}</div>
      </div>

      <div class="footer">
        <p>${escapeHtml(l.footer)}</p>
        <p>www.plagiacheck.online</p>
      </div>
    </body>
    </html>
  `

  return openPrintWindow(html)
}

/**
 * Opens the report in a new window and triggers the print dialog.
 * Returns false when the popup was blocked so callers can tell the user
 * instead of toasting a false success.
 */
function openPrintWindow(html: string): boolean {
  const printWindow = window.open("", "_blank")
  if (!printWindow) return false

  printWindow.document.write(html)
  printWindow.document.close()

  // For a document.write'd about:blank the load event may already have
  // fired by the time we could assign onload — schedule print directly
  // once the current tick's parsing has settled.
  setTimeout(() => {
    try {
      printWindow.focus()
      printWindow.print()
    } catch {
      // Window was closed before printing — nothing to do.
    }
  }, 250)
  return true
}
